# Site settings
title: "Rafael Gomes Resume"
description: "Gomex's resume."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "true"
resume_name:                    "Rafael Brito Gomes"
resume_title:                   "DevOps Engineer"
resume_contact_email:
  "linux.rafa@gmail.com"
resume_header_contact_info: "Salvador - BA, Brasil | linux.rafa@gmail.com"

resume_header_intro: "<p>I'm DevOps Engineer, technical writer and speaker. It has been a long time since I felt in love with Linux and, while that I had the opportunity to work as a developer infrastructure using Puppet, Chef, Ansible, Docker. One of the benefits of working as a DevOps Engineer was that I'm able to understand how developers think and help then.</p>
<p>Author of a book 'Docker para desenvolvedores' (Portuguese version): https://leanpub.com/dockerparadesenvolvedores</p>
<p>Docker for developers (English version - Under construction): https://leanpub.com/docker-for-developers</p>
<p>Docker Captain: https://www.docker.com/community/docker-captains</p>
<p>Besides being comfortable with Linux, Ansible, Docker, Kubernetes and AWS I have also skills with python, monitoring and security.</p>"

# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_talks:          true
resume_section_recognition:     false
resume_section_links:           true
resume_section_associations:    true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/gomex"
  resume_twitter_url:           "http://twitter.com/gomex"
  #resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  resume_linkedin_url:          "https://www.linkedin.com/in/rbgomes"
  # resume_instagram_url:         "insert your Instagram URL here"
  resume_website_url:           "http://techfree.com.br"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
